// <auto-generated />
namespace JeffERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class customers_and_parts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customers_and_parts));
        
        string IMigrationMetadata.Id
        {
            get { return "201702190243450_customers_and_parts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
